#
# ----------------------------
# 数据库配置 / Database Config's:
# ----------------------------

# 这是数据库URL / This is the database url
# 如果启动时报错，请设置 serverTimezone；它用于避免夏令时切换时的时间戳错误。 / Set the serverTimezone value if you get an error during startup. It is needed to avoid timestamp errors during daylight savings clock change.
database.url = jdbc:mysql://localhost:3309/aion_cs?serverTimezone=&characterEncoding=UTF-8

# 数据库用户 / Database user
database.user = aion_cs

# 数据库密码 / Database password
database.password = 123456

# 连接池保留的最大连接数 / Maximal amount of connections kept in connection pool
database.connectionpool.connections.max = 5

# 获取数据库连接时抛出超时错误前的最大等待时间 / Maximum wait time when getting a DB connection, before throwing a timeout error
database.connectionpool.timeout = 5000
