#
# ----------------------------
# 网络配置 / Network Config's:
# ----------------------------

# Aion客户端尝试连接的地址（格式为 host:port）。 / Address where Aion clients will attempt to connect to (format is host:port).
# 由于客户端不支持IPv6，主机部分可以是IPv4地址或解析到IPv4地址的主机名/域名。 / The host part can be an IPv4 address or a host/domain name which resolves to an IPv4 address since the client does not support IPv6.
# 默认情况下，连接地址与socket地址相同（如果主机部分设置为0.0.0.0，服务器会自动选择最合适的本地 / By default, the connect address is the same as the socket address (if the host part is set to 0.0.0.0 the server will auto select the most suitable local
# IPv4地址并记录到日志）。 / IPv4 address and log it).
chatserver.network.client.connect_address = ${chatserver.network.client.socket_address}

# 聊天服务器监听Aion客户端连接的本地地址（0.0.0.0 = 绑定任意本地IP） / Local address where CS will listen for Aion client connections (0.0.0.0 = bind any local IP)
chatserver.network.client.socket_address = 0.0.0.0:10241

# 聊天服务器监听游戏服务器连接的本地地址（0.0.0.0 = 绑定任意本地IP） / Local address where CS will listen for GS connections (0.0.0.0 = bind any local IP)
chatserver.network.gameserver.socket_address = 0.0.0.0:9021

# 用于游戏服务器成功认证的匹配密码 / Password to match for successful authentication of the game server
# 注意：不要忘记填写密码！ / NOTE: Don't forget to add your password!
chatserver.network.gameserver.password =

# 仅用于读写网络数据的额外线程数。 / Number of extra threads dedicated only to read/write network data.
# 值小于1表示接收线程也会处理读写。 / Value < 1 means that acceptor thread will also handle read & write.
# 值大于0表示会有 x 个专用读写线程 + 1 个接收线程。 / Value > 0 means there will be x dedicated read/write threads + 1 acceptor.
chatserver.network.nio.threads = 1
