#

# 将服务器错误和警告发送到 Discord 频道（更多配置见 logback.xml） / Send server errors and warnings to a Discord channel (see logback.xml for further configuration)
# 默认值：空（停用） / Default: empty (deactivated)
loginserver.log.status.discord.webhook_url =
# 头像URL会插入 logback.xml 的转换模式，因此可以使用 Logback 变量，例如 %level（见 / The avatar url is inserted in the conversion pattern in logback.xml and therefore can use Logback variables, such as %level (see
# http://logback.qos.ch/manual/layouts.html#conversionWord），以便按严重程度设置不同头像。 / http://logback.qos.ch/manual/layouts.html#conversionWord) to set different avatars depending on the severity.
loginserver.log.status.discord.avatar_url =

# 将成功的游戏服务器登录及连接数据记录到数据库 / Log successful game server logins including connection data to DB
# 默认值：false / Default: false
loginserver.log.logins = false
