#

# 将服务器错误和警告发送到 Discord 频道（更多配置见 logback.xml） / Send server errors and warnings to a Discord channel (see logback.xml for further configuration)
# 默认值：空（停用） / Default: empty (deactivated)
chatserver.log.status.discord.webhook_url =
# 头像URL会插入 logback.xml 的转换模式，因此可以使用 Logback 变量，例如 %level（见 / The avatar url is inserted in the conversion pattern in logback.xml and therefore can use Logback variables, such as %level (see
# http://logback.qos.ch/manual/layouts.html#conversionWord），以便按严重程度设置不同头像。 / http://logback.qos.ch/manual/layouts.html#conversionWord) to set different avatars depending on the severity.
chatserver.log.status.discord.avatar_url =

# 记录客户端的每个频道请求（调试用途） / log each channel request from client (debug purposes)
chatserver.log.channel.request = false

# 记录对无效频道的请求（调试用途） / Log requests to invalid channels (debug purposes)
chatserver.log.channel.invalid = false

# 是否记录聊天？ / Log chat?
chatserver.log.chat = false

# 将全局聊天消息发送到 Discord 频道，仅在聊天日志启用时生效（更多配置见 logback.xml） / Send global chat messages to a discord channel, only active when chat logging is enabled (see logback.xml for further configuration)
# 默认值 = 空（停用） / Default = empty (deactivated)
chatserver.log.chat.discord.webhook_url =
# 使用当前 logback.xml 转换模式时，可在头像URL中使用 $2 为不同阵营设置头像；$2 会解析为 / With the current conversion pattern in logback.xml, $2 can be used in the avatar url to use different avatars per faction. $2 will resolve to
# E 表示天族，A 表示魔族 / E for Elyos and A for Asmodians
# 示例：https://your-server.com/img/discord_avatar_faction_$2.png / Example: https://your-server.com/img/discord_avatar_faction_$2.png
chatserver.log.chat.discord.avatar_url =

# 是否将聊天记录到数据库？ / Log chat to DB?
chatserver.log.chat_to_db = false
