#
# ----------------------------
# 封包洪泛过滤配置 / Packet flood filter configs:
# ----------------------------

# 封包洪泛处理方式 / Packet flood handling
# 0 - 关闭 / 0 - off
# 1 - 记录日志消息 / 1 - log message
# 2 - 记录日志消息并断开客户端 / 2 - log message and disconnect client
# 默认值：1 / Default: 1
gameserver.network.pff.mode = 1

# 下面可以列出封包操作码及其毫秒阈值；如果封包到达速度快于阈值，将根据 / Below you can list packet opcodes followed by a threshold in milliseconds. If a packet comes in faster than the threshold, action is taken depending
# 上方配置的模式执行操作。 / on the above configured mode.
# 格式为 "gameserver.network.pff.packet.<opcode> = <msec>" / Schema is "gameserver.network.pff.packet.<opcode> = <msec>"
# 示例：gameserver.network.pff.packet.0x0C4 = 150 / Example: gameserver.network.pff.packet.0x0C4 = 150

# CM_CASTSPELL（施法封包） / CM_CASTSPELL
# gameserver.network.pff.packet.0x0C4 = 150