#
# ----------------------------
# 网络配置 / Network Config's:
# ----------------------------

# 登录服务器监听Aion客户端连接的本地地址（0.0.0.0 = 绑定任意本地IP） / Local address where LS will listen for Aion client connections (0.0.0.0 = bind any local IP)
loginserver.network.client.socket_address = 0.0.0.0:2106

# 玩家因暴力破解被封禁前可尝试登录的次数 / How many times player can try to login before he get's banned for brute-forcing
loginserver.network.client.logintrybeforeban = 5

# 发生暴力破解时玩家应被封禁的分钟数 / For what time in minutes the player should be banned in case of brute-forcing
loginserver.network.client.bantimeforbruteforcing = 15

# 登录服务器监听游戏服务器连接的本地地址（0.0.0.0 = 绑定任意本地IP） / Local address where LS will listen for GS connections (0.0.0.0 = bind any local IP)
loginserver.network.gameserver.socket_address = 0.0.0.0:9014

# 仅用于读写网络数据的额外线程数。 / Number of extra threads dedicated only to read/write network data.
# 值小于1表示接收线程也会处理读写。 / Value < 1 means that acceptor thread will also handle read & write.
# 值大于0表示会有 x 个专用读写线程 + 1 个接收线程。 / Value > 0 means there will be x dedicated read/write threads + 1 acceptor.
loginserver.network.nio.threads = 0

# 登录时是否自动创建账号？ / Create accounts automatically on login or not?
# 默认值：true / Default: true
loginserver.accounts.autocreate = true

# 外部认证URL / URL for external authentication
# 启用后，登录凭据会由外部系统校验，不会存储在登录服务器数据库中。 / With this login credentials will be checked externally and not be stored in LS DB.
# 登录服务器会通过HTTP POST将从客户端收到的凭据作为JSON负载发送到远程认证服务器： / Login server will send credentials it received from the client via HTTP POST as a JSON payload to the remote authentication server:
# {
#   "user": string,
#   "password": string
# }
# 远程认证服务器必须返回以下结构的JSON： / The remote authentication server must then respond with a JSON with the following structure:
# {
# 	"accountId": string // unique user id or name that will be used to identify the LS user account; should be null if not authed
# 	"aionAuthResponseId": number // auth state (see com.aionemu.loginserver.network.aion.AionAuthResponse), must be zero if authed
# }
# 如果响应包含有效ID，该账号会登录；否则会将给定状态返回给客户端。 / If the response contains a valid id, the account will be logged in, otherwise the given state will be returned to the client.
# 注意：请将 loginserver.accounts.autocreate 设为 true，否则新用户无法登录 / Note: Set loginserver.accounts.autocreate to true, otherwise new users can't log in
# 默认值：空（停用） / Default: empty (deactivated)
loginserver.accounts.external_auth.url =

# 启用账号登录时针对单个IP的暴力破解保护 / Enable brute-force protector from 1 IP on account login
# 默认值：true / Default: true
loginserver.server.bruteforceprotector = true
