#
# ----------------------------
# AI配置 / AI config's:
# ----------------------------

# 启用NPC移动 / Enable NPC movement
# 默认值：true / Default: true
gameserver.npcmovement.enable = true

# NPC再次移动前等待的最短时间（秒）。 / The minimum time in seconds that the NPC waits before moving again.
# 默认值：3 （秒） / Default: 3 (seconds)
gameserver.npcmovement.delay.minimum = 3

# NPC再次移动前等待的最长时间（秒）。 / The maximum time in seconds that the NPC waits before moving again.
# 默认值：15 （秒） / Default: 15 (seconds)
gameserver.npcmovement.delay.maximum = 15

# 启用NPC喊话 / Enable NPC shouts
# 默认值：false / Default: false
gameserver.npcshouts.enable = false

# AI *.java处理器目录 / Location of AI *.java handlers
gameserver.ai.handler_directory = ./data/handlers/ai

# ----------------------------
# AI调试（开发者）配置 / AI debug (developer) config's:
# ----------------------------

# 生成带有日志属性的AI NPC / Spawn AI NPCs with activated logging attribute
# 默认值：false / Default: false
gameserver.ai.oncreate.debug = false

# 记录启用日志NPC的移动 / Log movement for logging enabled NPCs
# 默认值：true / Default: true
gameserver.ai.move.debug = true

# 在NPC对象中保存AI事件日志（可通过 //ai2 命令获取） / Save AI event log in NPC objects (can be retrieved via //ai2 command)
# 默认值：false / Default: false
gameserver.ai.event.debug = false