#
# ----------------------------
# 自动组队配置 / AutoGroup config's:

# 启用自动组队 / Enable Auto Group
# 默认值：true / Default: true
gameserver.autogroup.enable = true

# 启用PvP竞技场开始时间检查 / Enable check start time for pvp arenas
# 默认值：true / Default: true
gameserver.startTime.enable = true

# 德雷得奇安报名时长 / Dredgion registration period
# 默认值：60 min / Default: 60 min
gameserver.dredgion.registration_period = 60

# 德雷得奇安开始时间 / Dredgion start times
# 逗号分隔的cron表达式列表（包含逗号的表达式必须加引号） / Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 默认值："0 0 0,12,20 ? * *" / Default: "0 0 0,12,20 ? * *"
gameserver.dredgion.time = "0 0 0,12,20 ? * *"

# 卡马尔战场报名时长 / Kamar Battlefield registration period
# 默认值：60 min / Default: 60 min
gameserver.kamar_battlefield.registration_period = 60

# 卡马尔战场开始时间 / Kamar Battlefield start times
# 逗号分隔的cron表达式列表（包含逗号的表达式必须加引号） / Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 默认值："0 0 0,20 ? * MON,WED,SAT" / Default: "0 0 0,20 ? * MON,WED,SAT"
gameserver.kamar_battlefield.time = "0 0 0,20 ? * MON,WED,SAT"

# 欧菲丹大桥报名时长 / Engulfed Ophidan Bridge registration period
# 默认值：60 min / Default: 60 min
gameserver.engulfed_ophidan_bridge.registration_period = 60

# 欧菲丹大桥报名开始时间 / Engulfed Ophidan Bridge registration start times
# 逗号分隔的cron表达式列表（包含逗号的表达式必须加引号） / Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 默认值：0 0 12,19 ? * * / Default: 0 0 12,19 ? * *
gameserver.engulfed_ophidan_bridge.time = "0 0 12,19 ? * *"

# 铁壁堡垒战场报名时长 / Iron Wall Warfront registration period
# 默认值：60 min / Default: 60 min
gameserver.iron_wall_warfront.registration_period = 60

# 铁壁堡垒战场报名开始时间 / Iron Wall Warfront registration start times
# 逗号分隔的cron表达式列表（包含逗号的表达式必须加引号） / Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 默认值："0 0 0,12 ? * SUN" / Default: "0 0 0,12 ? * SUN"
gameserver.iron_wall_warfront.time = "0 0 0,12 ? * SUN"

# 伊德gel圆顶竞技场报名时长 / Idgel Dome registration period
# 默认值：60 min / Default: 60 min
gameserver.idgel_dome.registration_period = 60

# 伊德gel圆顶竞技场报名开始时间 / Idgel Dome registration start times
# 逗号分隔的cron表达式列表（包含逗号的表达式必须加引号） / Comma separated list of cron expressions (expressions containing commas must be put in quotes)
# 默认值：0 0 23 ? * * / Default: 0 0 23 ? * *
gameserver.idgel_dome.time = 0 0 23 ? * *

# 向敌对阵营公告战场报名 / Announce battlefield registrations to the enemy faction
# 默认值：false / Default: false
gameserver.autogroup.announce_battleground_registrations = false