#
# ----------------------------
# 数据库清理配置 / Database Cleaning config's:
# ----------------------------

# 启用数据库清理 / Enable Database Cleaning
# 默认值：false / Default: false
gameserver.cleaning.enable = false

# 账号不活跃达到多少天后删除角色 / Minimum account inactivity in days, after which chars get deleted
# 仅当该值大于30时才会执行清理 / Cleaning will only be executed with a value greater than 30
# 默认值：365 / Default: 365
gameserver.cleaning.min_account_inactivity = 0

# 每个账号上会被删除角色的最高等级 / Maximum level of characters that will be deleted on each account
# 默认值：25 / Default: 25
gameserver.cleaning.max_level = 25