#
# ----------------------------
# 制作配置 / Craft config's:
# ----------------------------

# 玩家登录时启用移除多余技能 / Enable remove excess skills on player log in
# 默认值：false / Default: false
gameserver.craft.skills.delete.excess.enable = false

# 玩家可拥有的专家技能最大数量 / Maximum number of expert skills a player can have
# 默认值：2 / Default: 2
gameserver.craft.max.expert.skills = 2

# 玩家可拥有的大师技能最大数量 / Maximum number of master skills a player can have
# 默认值：1 / Default: 1
gameserver.craft.max.master.skills = 1

# 允许奥德/精气采集技能提升到499点以上 / Enable leveling of aether and essence tapping skills above 499 points
# 默认值：false / Default: false
gameserver.craft.disable.tapping.cap = false

gameserver.craft.fail.chance = 33

gameserver.gather.fail.chance = 33