#
# ----------------------------
# 自定义配置 / Custom config's:
# ----------------------------

# 启用挑战任务 / Enable challenge tasks
# 默认值：true / Default: true
gameserver.challenge.tasks.enabled = true

# 玩家成功将物品强化到+15或+20时公告 / Announce when a player successfully enchants an item to +15 or +20
# 默认值：true / Default: true
gameserver.enchant.announce.enable = true

# 允许阵营间发言 / Enable speaking between factions
# 默认值：false / Default: false
gameserver.chat.factions.enable = true

# 使用密语的最低等级 / Minimum level to use whisper
# 默认值：10 / Default: 10
gameserver.chat.whisper.level = 1

# 经纪人中物品多少天后下架（客户端无法显示超过255天） / Time in days after which an item in broker will be unregistered (client cannot display more than 255 days)
# 默认值：8 / Default: 8
gameserver.broker.registration_expiration_days = 8

# 允许对立阵营在敌方领地绑定 / Allow opposite factions to bind in enemy territories
# 默认值：false / Default: false
gameserver.cross.faction.binding = false

# 启用无需任务的二转 / Enable second class change without quest
# 默认值：false / Default: false
gameserver.simple.secondclass.enable = false

# 禁用连锁触发概率（连锁技能100%成功） / Disable chain trigger rate (chain skill with 100% success)
# 默认值：false / Default: false
gameserver.skill.chain.disable_triggerrate = false

# 启用骑乘限制 / Enable ride restriction
# 默认值：true / Default: true
gameserver.ride.restriction.enable = false

# 玩家默认飞行时间 / Default player fly time
# 默认值：60 （1分钟） / Default: 60 (1 minute)
gameserver.base.flytime = 900

# 启用导师组队无AP。 / Enable no AP in mentored group.
# 默认值：false / Default: false
gameserver.noap.mentor.group = false

# 启用单个复活石限制 / Enable one kisk restriction
# 默认值：true / Default: true
gameserver.kisk.restriction.enable = false

# ----------------------------
# PvP配置 / PvP config's:
# ----------------------------
# 限制玩家重复击杀同一玩家的时间（毫秒） / Time in milliseconds in which players are limited for killing one player
# 默认值：86400000 （1天） / Default: 86400000 (1 day)
gameserver.pvp.dayduration = 86400000

# 24小时内对同一玩家可获得正常AP的最大PvP击杀次数，之后每次击杀只获得1AP。 / Maximum number of pvp kills on one player before receiving 1AP per kill in a 24 hour period.
# 默认值：5 / Default: 5
gameserver.pvp.maxkills = 5

# 启用PvP击杀奖励 / Enable the rewards for pvp kills
# 默认值：false / Default: false
# （启用前请重置 abyss_rank 表中的 all_kill） / (Reset all_kill from abyss_rank table before activate it)
gameserver.kill.reward.enable = false

# 在极乐世界斗技场或伏魔殿特里尼尔斗技场被击杀时保留增益 / Keep buffs when getting killed in Sanctum's Coliseum or Pandaemonium's Triniel Coliseum
# 默认值：false / Default: false
gameserver.coliseum.keep_buffs = false

# ----------------------------
# 裂缝配置 / Rifts config's:
# ----------------------------
gameserver.rift.enable = true
gameserver.rift.duration = 1

# ----------------------------
# 次元漩涡配置 / Dimensional Vortex config's:
# ----------------------------
gameserver.vortex.enable = true
gameserver.vortex.brusthonin.schedule = 0 0 16 ? * SAT
gameserver.vortex.theobomos.schedule = 0 0 16 ? * SUN
gameserver.vortex.duration = 2

# ----------------------------
# 征服者与守护者系统 / Conqueror & Protector system:
# ----------------------------
gameserver.cp.enable = true
gameserver.cp.worlds = 210020000,210040000,210050000,210070000,220020000,220040000,220070000,220080000
gameserver.cp.level.diff = 5
gameserver.cp.kills.decrease_interval_minutes = 10
gameserver.cp.kills.decrease_count = 1
gameserver.cp.kills.rank1 = 1
gameserver.cp.kills.rank2 = 10
gameserver.cp.kills.rank3 = 20

# ----------------------------
# 限制配置 / Limits config:
# ----------------------------
# 启用限制 / Enable limits
# 默认值：true / Default: true
gameserver.limits.enable = true

# 启用动态上限：启用后，在最终达到限制前，可以出售一件会超出限制的物品 / Enable dynamic cap: When active, you can sell one item that would exceed your limit, before you finally reach it
# 默认值：false / Default: false
gameserver.limits.enable_dynamic_cap = false

# 限制更新时间 / Limit update time
# 默认值：每天00:00 / Default: 00:00 everyday
gameserver.limits.update = 0 0 0 ? * *

# ----------------------------
# 上限配置 / Cap config's:
# ----------------------------
# 启用基纳上限 / Enable Kinah capping
# 默认值：false / Default: false
gameserver.enable.kinah.cap = false

# 基纳上限值 / Cap value for Kinah
# 默认值：999999999 / Default: 999999999
gameserver.kinah.cap.value = 999999999

# 启用AP上限 / Enable AP capping
# 默认值：false / Default: false
gameserver.enable.ap.cap = false

# AP上限值 / Cap value for AP
# 默认值：1000000 / Default: 1000000
gameserver.ap.cap.value = 1000000

# ----------------------------
# 好友列表配置 / Friendlist config's:
# ----------------------------
# 好友列表大小（最大90） / Friendlist size (max 90)
# 默认值：90 / Default: 90
gameserver.friendlist.size = 90

# 限制GM，使其好友列表中不能有非GM / Restrict GMs so they can not have non-GMs on their list
# 默认值：false / Default: false
gameserver.friendlist.gm_restrict = false

# ----------------------------
# 容量配置 / Size config's:
# ----------------------------
# 允许配置玩家可接取普通任务数量上限 / Allow to configure size limit of basic quests that player can get up
# 默认值：40 / Default: 40
gameserver.basic.questsize.limit = 100

# 允许的背包扩展总次数 / Total number of allowed cube expansions
# 默认值：11 / Default: 11
gameserver.cube.expansion_limit = 11

# 允许配置NPC扩展的背包大小限制 / Allow to configure cube size limit of npc expands
# 默认值：5 / Default: 5
gameserver.npcexpands.limit = 11

# ----------------------------
# 搜索配置 / Search config's:
# ----------------------------
# 允许搜索对立阵营玩家 / Enable searching players of opposite faction
# 默认值：false / Default: false
gameserver.search.factions.mode = false

# 搜索玩家时显示GM列表 / Enable list gm when searching players
# 默认值：false / Default: false
gameserver.search.gm.list = false

# 使用搜索的最低等级 / Minimum level to use search
# 默认值：10 / Default: 10
gameserver.search.player.level = 1

# ----------------------------
# 深渊变身登出后处理 / Abyss Xform after logout
# 启用或禁用登出后深渊变身持续时间倒计时 / Enable or Disable counting down of duration after logout of Abyss transformations
# ----------------------------
gameserver.abyssxform.afterlogout = false

# ----------------------------
# .faction命令 / .faction Command
# ----------------------------
# 基纳价格 / Kinah price
gameserver.faction.price = 10000
# 启用该命令 / Enable the command
gameserver.faction.cmdchannel = true
# 使用聊天服务器频道 / Use chat server channels
gameserver.faction.chatchannels = false

# 启用出售AP物品 / Enable selling ap items
# 默认值：true / Default: true
gameserver.selling.apitems.enabled = true

# 角色将在多少分钟后删除。 / Time in minutes after which character will be deleted.
# 默认值：5 / Default: 5
character.deletion.time.minutes = 2

# HP/MP已满时不消耗药水 / Don't consume potions when already at full HP/MP
# 默认值：false / Default: false
gameserver.items.ignore_potions_at_full_health = false

# ----------------------------
# 新手礼包 / Starter Kit:
# ----------------------------
# 启用新手礼包 / Enable starter kit
# 默认值：false / Default: false
gameserver.custom.starter_kit.enable = true

# 允许通过 .pvp 聊天命令加入自定义PvP地图 / Enables joining the custom PvP map via .pvp chat command
# 默认值：false / Default: false
gameserver.pvpmap.enable = false

# 自定义PvP地图的PvP AP倍率。 / PvP AP multiplier for our custom PvP-Map.
# 注意：该值还会与玩家倍率相乘！ / Keep in mind that this value is also multiplied with players rates!
# 默认值：2（等于当前倍率下的x4） / Default: 2 (equals x4 for our current rates)
gameserver.pvpmap.apmultiplier = 2

# 自定义PvP地图的PvE AP倍率。 / PvE AP multiplier for our custom PvP-Map.
# 注意：该值还会与玩家倍率相乘！ / Keep in mind that this value is also multiplied with players rates!
# 默认值：1 / Default: 1
gameserver.pvpmap.pve.apmultiplier = 1

# 自定义PvP地图的随机BOSS刷新概率 / Random boss spawn rate for our custom PvP-Map
# 注意：该值会按以下因素增加： / Keep in mind that this value is increased by the
# 在线玩家数量（每名玩家+2%，上限30%） / amount of online players(+2% per player, cap 30%)
# 默认值：40（在线玩家最多+30%奖励 = 70） / Default: 40 (+30% max online player bonus = 70)
gameserver.pvpmap.random_boss.rate = 40

# 自定义PvP地图的随机BOSS刷新时间 / Random boss spawn time for our custom PvP-Map
# 默认值：0 30 14,18,21 ? * * / Default: 0 30 14,18,21 ? * *
gameserver.pvpmap.random_boss.time = 0 30 14,18,21 ? * *

# ----------------------------
# 神石 / Godstones:
# ----------------------------
# 默认值：1.0 / Default: 1.0
gameserver.rates.godstone.activation.rate = 1.0

# 两次神石触发评估之间的等待时间（毫秒）。 / Wait time in milliseconds between evaluations of a Godstone activation.
# 默认值：750 / Default: 750
gameserver.rates.godstone.evaluation.cooldown_millis = 750


# 累计抗性中计入召唤物施加的异常效果。 / Count summon-applied abnormal effects for cumulative resist.
# 官方行为：false / Retail behavior: false
gameserver.pvp.cumulative_resist.count_summon_effects = false
