#
# ----------------------------
# 掉落配置 / Drop config's:
# ----------------------------

# 当玩家掉落指定最低品质或更高品质物品时公告；留空则禁用掉落公告 / Announce when a player drops an item with the given minimum item quality (or higher). Leave empty to disable drop announces
# 可选值：JUNK、COMMON、RARE、LEGEND、UNIQUE、EPIC 或 MYTHIC / Possible values: JUNK, COMMON, RARE, LEGEND, UNIQUE, EPIC or MYTHIC
# 默认值：MYTHIC / Default: MYTHIC
gameserver.drop.announce_quality = MYTHIC

# 逗号分隔的地图ID列表；在这些地图中队伍成员可在全地图范围掷骰掉落，而不是默认范围 / Comma separated list of map ids where team members can roll for drops anywhere on the map instead of in the default range
# 默认值： / Default:
gameserver.drop.disable_range_check_maps =