#
# ----------------------------
# 坠落伤害配置 / Fall damage config's:
# ----------------------------

# 每米造成的伤害百分比。 / The damage percentage per meter.
# 默认值：1.0 (%) / Default: 1.0 (%)
gameserver.falldamage.percentage = 1.0

# 会受到伤害的最小坠落高度。 / Minimum fall height to receive damage.
# 默认值：10 （米） / Default: 10 (meter)
gameserver.falldamage.distance.minimum = 10

# 落地时会死亡的最大坠落高度。 / Maximum fall height on which you will die when you hit the ground.
# 默认值：50 （米） / Default: 50 (meter)
gameserver.falldamage.distance.maximum = 50

# 超过后会在空中死亡的最大坠落高度。 / Maximum fall height after which you will die in mid air.
# 默认值：200 （米） / Default: 200 (meter)
gameserver.falldamage.distance.midair = 200