#
# ----------------------------
# 地理数据配置 / Geodata config's:
# ----------------------------

# 启用地理数据（高度和网格） / Enable Geodata (heights and meshes)
# 默认值：true / Default: true
gameserver.geodata.enable = true

# 启用基于地理数据的可见性检查。 / Enable canSee checks using geodata.
# 默认值：true / Default: true
gameserver.geodata.cansee.enable = true

# 启用恐惧技能的地理数据处理。 / Enable fear skill using geodata.
# 默认值：true / Default: true
gameserver.geodata.fear.enable = true

# 启用后，如果目标在飞行，NPC移动时会基于地理数据检查Z坐标 / If enabled - during movements npcs will be checking z coordinate based on geo if target is flying
# 默认值：true / Default: true
gameserver.geodata.npc.move = true

# 启用技能使用地理材质 / Enable geo materials using skills
# 默认值：true / Default: true
gameserver.geodata.materials.enable = true

# 向GM显示碰撞区域名称和技能ID / Show collision zone name and skill id for GMs
# 默认值：false / Default: false
gameserver.geodata.materials.showdetails = false

# 启用地理数据护盾 / Enable geodata shields
# 默认值：true / Default: true
gameserver.geodata.shields.enable = true