#
# ----------------------------
# 小队配置 / Group config's:
# ----------------------------

# 小队成员断线后被移除的时间（秒） / Time in seconds after a group member is removed after disconnect
# 默认值：600 (10 minutes) / Default: 600 (10 minutes)
gameserver.playergroup.removetime = 600

# 队员获得击杀怪物经验的最大距离 / Maximum distance between killed monster and party member to receive XP
# 默认值：100 / Default: 100
gameserver.playergroup.maxdistance = 100

# 允许邀请其他阵营玩家加入小队 / Enable inviting to group player from other faction
# 默认值：false / Default: false
gameserver.group.inviteotherfaction = false

# ----------------------------
# 联盟配置 / Alliance config's:
# ----------------------------
# 联盟成员断线后被移除的时间（秒） / Time in seconds after a alliance member is removed after disconnect
# 默认值：600 (10 minutes) / Default: 600 (10 minutes)
gameserver.playeralliance.removetime = 600

# 允许邀请其他阵营玩家加入联盟 / Enable inviting to alliance player from other faction
# 默认值：false / Default: false
gameserver.playeralliance.inviteotherfaction = false

# 即使不在副本入口，也允许在寻找组队窗口申请或登记副本队伍（类似6.2+版本） / Allow applying for or registering instance groups in the Find Group window even if you're not at the instance entrance (like in version 6.2+)
# 默认值：false / Default: false
gameserver.instance_group.form_anywhere = false