#
# ----------------------------
# HTML配置 / HTML config's:
# ----------------------------

# 启用HTML欢迎消息 / Enable HTML welcome message
# 默认值：false / Default: false
gameserver.html.welcome.enable = false

# 启用HTML指南系统 / Enable HTML Guides system
# 默认值：false / Default: false
gameserver.html.guides.enable = false

# HTML文件目录 / Html files directory
# 默认值：./data/static_data/HTML/ / Default: ./data/static_data/HTML/
gameserver.html.root = ./data/static_data/HTML/

# HTML缓存目录 / Html cache directory
# 默认值：./cache/html.cache / Default: ./cache/html.cache
gameserver.html.cache.file = ./cache/html.cache

# 编码 / Encoding
# 默认值：UTF-8 / Default: UTF-8
gameserver.html.encoding = UTF-8