#

# 将服务器错误和警告发送到 Discord 频道（更多配置见 logback.xml） / Send server errors and warnings to a Discord channel (see logback.xml for further configuration)
# 默认值：空（停用） / Default: empty (deactivated)
gameserver.log.status.discord.webhook_url =
# 头像URL会插入 logback.xml 的转换模式，因此可以使用 Logback 变量，例如 %level（见 / The avatar url is inserted in the conversion pattern in logback.xml and therefore can use Logback variables, such as %level (see
# http://logback.qos.ch/manual/layouts.html#conversionWord），以便按严重程度设置不同头像。 / http://logback.qos.ch/manual/layouts.html#conversionWord) to set different avatars depending on the severity.
gameserver.log.status.discord.avatar_url =

# 启用audit logging / Enable audit logging
# 默认值：true / Default: true
gameserver.log.audit = true

# 启用craft logging / Enable craft logging
# 默认值：true / Default: true
gameserver.log.craft = false

# 启用玩家 exchange logging / Enable player exchange logging
# 默认值：false / Default: false
gameserver.log.player.exchange = false

# 启用Broker exchange logging / Enable Broker exchange logging
# 默认值：false / Default: false
gameserver.log.broker.exchange = false

# 启用gmaudit logging (聊天命令, gm whispers, ...) / Enable gmaudit logging (chat commands, gm whispers, ...)
# 默认值：true / Default: true
gameserver.log.gmaudit = true

# 启用general chat logging (public, group, shout, ...) / Enable general chat logging (public, group, shout, ...)
# 默认值：true / Default: true
gameserver.log.chats.general = true

# 启用private chat logging (legion & whisper) / Enable private chat logging (legion & whisper)
# 默认值：false / Default: false
gameserver.log.chats.private = false

# 启用物品 logging / Enable item logging
# 默认值：true / Default: true
gameserver.log.item = true

# 启用kill logging / Enable kill logging
# 默认值：false / Default: false
gameserver.log.kill = false

# 启用PowerLeveling logging / Enable PowerLeveling logging
# 默认值：false / Default: false
gameserver.log.pl = false

# 启用mail logging / Enable mail logging
# 默认值：false / Default: false
gameserver.log.mail = false

# 启用要塞战 logging / Enable siege logging
# 默认值：false / Default: false
gameserver.log.siege = false

# 启用sysmail logging / Enable sysmail logging
# 默认值：false / Default: false
gameserver.log.sysmail = false

# 启用house auction result logging / Enable house auction result logging
# 默认值：true / Default: true
gameserver.log.auction = true

# 启用tampering log / Enable tampering log
# 默认值：false / Default: false
gameserver.log.tampering = false
