#
# ----------------------------
# 会员配置 / Membership config's:
# ----------------------------
#
# 此文件中的选项会对达到指定会员等级或更高等级的玩家启用。 / Options in this file are enabled for players with the given membership level or above.
# 0表示普通玩家，因为这是新玩家的默认会员等级 / 0 means regular players, since it's the default membership of new players
# 1表示会员等级1的玩家，依此类推 / 1 means players with membership level 1 and so on

# 登录通知使用的会员名称列表，逗号分隔，从会员1的名称开始 / Comma separated membership names for notification on login, starting with the name for membership 1
# 默认值：Premium / Default: Premium
gameserver.membership.types = Premium

# 允许骑乘坐骑时采集 / Allow gathering while riding a mount
# 默认值：10 / Default: 10
gameserver.membership.gathering.allow_on_mount = 10

# 禁用副本称号要求 / Disable instances title requirement
# 默认值：10 / Default: 10
gameserver.instances.title.requirement = 10

# 禁用副本种族要求 / Disable instances race requirement
# 默认值：10 / Default: 10
gameserver.instances.race.requirement = 10

# 禁用副本等级要求 / Disable instances level requirement
# 默认值：10 / Default: 10
gameserver.instances.level.requirement = 10

# 禁用副本组队要求 / Disable instances group requirement
# 默认值：10 / Default: 10
gameserver.instances.group.requirement = 10

# 禁用副本任务要求 / Disable instances quest requirement
# 默认值：10 / Default: 10
gameserver.instances.quest.requirement = 10

# 减少副本冷却时间 / Decrease instances cooldowns
# 默认值：10 / Default: 10
gameserver.instances.cooldown = 10

# 开放所有表情 / All emotions available
# 默认值：10 / Default: 10
gameserver.emotions.all = 10

# 普通/高级烙印槽不需要任务 / Not require quest for normal/advanced stigma slots
# 默认值：10 / Default: 10
gameserver.quest.stigma.slot = 10

# 禁用灵魂疾病（死亡后的减益） / Disable soulsickness (debuf after death)
# 默认值：10 / Default: 10
gameserver.soulsickness.disable = 10

# 启用烙印自动学习模式 / Enable stigma auto learn mode
# 默认值：10 / Default: 10
gameserver.autolearn.stigma = 10

# 禁用任务数量限制 / Disable quest limit
# 默认值：10 / Default: 10
gameserver.quest.limit.disable = 10

# 启用每账号额外角色数量 / Enable additional count of characters per account
# 默认值：10 / Default: 10
gameserver.character.additional.enable = 10

# ----------------------------
# 会员选项 / Membership Options:
# ----------------------------
# 该会员等级的角色数量（最多8） / Count of characters for this membership (max 8)
# 默认值：8 / Default: 8
gameserver.character.additional.count = 8