#
# ----------------------------
# 定期保存间隔 / Periodic save intervals:
# ----------------------------
# 警告： / WARNING:
# 500名玩家在线时保存可能耗时最多10秒 / With 500 player online saving can be up to 10 seconds
# （取决于硬件、物品位置变化、新获得物品等） / (it depends on hardware, changes in item locations, new acquisitions etc)
# 通常建议的间隔为15-20分钟。 / Generally accepted interval is 15-20 minutes.

# 保存玩家数据（玩家、深渊军衔、任务、技能）的间隔（秒） / Time in seconds for saving player data (player, abyss rank, quests, skills)
# 默认值：900 (15 minutes) / Default: 900 (15 minutes)
gameserver.periodicsave.player.general = 900

# 保存玩家物品和物品魔石的间隔（秒） / Time in seconds for saving player items and item stones
# 默认值：900 (15 minutes) / Default: 900 (15 minutes)
gameserver.periodicsave.player.items = 900

# 保存军团仓库物品和物品魔石的间隔（秒） / Time in seconds for saving legion wh items and item stones
# 默认值：1200 (20 minutes) / Default: 1200 (20 minutes)
gameserver.periodicsave.legion.items = 1200

# 保存/更新宠物心情数据的间隔（秒） / Time in seconds for saving/updating pet mood data
# 默认值：10 / Default: 10
gameserver.periodicsave.player.pets = 10
