#
# ----------------------------
# 角色转移配置 / Player transfer config's:
# ----------------------------

# 如果玩家背包+仓库基纳超过此数量，则不能转移；0表示禁用 / if player exceeds this amount in inv+wh - we cant transfer him. 0 to disable
ptransfer.max.kinah = 0
# 天族绑定位置 / bind position for elyos
ptransfer.bindpoint.elyos = 210010000 1212.9423 1044.8516 140.75568 32
# 魔族绑定位置 / bind position for asmos
ptransfer.bindpoint.asmo = 220010000 571.0388 2787.3420 299.8750 32
# 允许转移表情 / allows to transfer emotions
ptransfer.allow.emotions = true
# 允许转移动作 / allows to transfer motions
ptransfer.allow.motions = true
# 允许转移宏 / allows to transfer macrosses
ptransfer.allow.macro = true
# 允许转移NPC阵营关系 / allows to transfer npc factions
ptransfer.allow.npcfactions = true
# 允许转移宠物 / allows to transfer pets
ptransfer.allow.pets = true
# 允许转移配方 / allows to transfer recipes
ptransfer.allow.recipes = true
# 允许转移技能 / allows to transfer skills
ptransfer.allow.skills = true
# 允许转移称号 / allows to transfer titles
ptransfer.allow.titles = true
# 允许转移任务 / allows to transfer quests
ptransfer.allow.quests = true
# 允许转移背包（方块） / allows to transfer inventory (cube)
ptransfer.allow.inventory = true
# 允许转移普通仓库 / allows to transfer regular warehouse
ptransfer.allow.warehouse = true
# 允许转移烙印石 / allows to transfer stigma stones
ptransfer.allow.stigma = true
# 如果目标服务器已有同名玩家，则阻止转移或使用前缀修改玩家名称 / if target server had player with same nickname - block or use prefix to change players name
ptransfer.block.samename = false
# 该玩家再次转移前需要等待的时间；0表示禁用 / time before which this player can be transferred again. 0 to disable
ptransfer.retransfer.hours = 0
# 转移时应移除的技能列表 / skill list should removed being transferred
# 要禁用此功能，请设置 ptransfer.remove.skills.list = * / to disable it set ptransfer.remove.skills.list = *
# 这表示会跳过该列表 / this will mean this list will be skipped
# 输入用逗号分隔的值，例如 ptransfer.remove.skills.list = 1,2,3,4 / enter values separated by ',' ptransfer.remove.skills.list = 1,2,3,4
ptransfer.remove.skills.list = *