#
# ----------------------------
# 价格配置 / Prices config's:
# ----------------------------

# 控制影响力标签中的“Prices:”值 / Controls the "Prices:" value in influence tab
# 默认值：100 / Default: 100
gameserver.prices.default.prices = 100

# 所有价格的隐藏修正值 / Hidden modifier for all prices
# 默认值：100 / Default: 100
gameserver.prices.default.modifier = 100

# 税率：值 = 100 + 税率百分比 / Taxes: value = 100 + tax %
# 默认值：100 / Default: 100
gameserver.prices.default.taxes = 100

# 默认值：100 / Default: 100
gameserver.prices.vendor.buymod = 100

# 默认值：20 / Default: 20
gameserver.prices.vendor.sellmod = 20