#
# ----------------------------
# 惩罚配置 / Punishment config's:
# ----------------------------

# 启用自动惩罚 / Enable auto punishment
# 默认值：false / Default: false
gameserver.punishment.enable = false

# 惩罚类型 / Punishment type
# 1 - 踢出 / 1 - kick
# 2 - 封禁角色 / 2 - ban character
# 3 - 封禁账号 / 3 - ban account
# 4 - 封禁IP / 4 - ban ip
# 5 - 封禁MAC / 5 - ban mac
# 默认值：1 / Default: 1
gameserver.punishment.type = 1

# 惩罚时长（分钟） / Punishment time in minutes
# 默认值：1440 （1天） / Default: 1440 (1 day)
gameserver.punishment.time = 1440