#
# ----------------------------
# 倍率配置 / Rate config's:
# ----------------------------

# 注意：所有值都可以是逗号分隔的整数或浮点数。 / NOTE: All values can be comma separated int or float values.
# 这样可以为任意数量的会员等级定义倍率 / This way you can define rates for any number of membership
# 类型。 / types you want to support.
# 每一项的索引对应一个会员等级。 / The index of each entry corresponds to one membership level.
# 因此 "1, 1.5, 2" 表示会员0使用x1倍率， / Therefore "1, 1.5, 2" means membership 0 uses x1 rates,
# 会员1使用x1.5倍率，会员2使用x2倍率，依此类推。 / membership 1 x1.5, membership 2 x2 and so on.
#
# 默认情况下，此配置包含两个会员等级的倍率 / By default, this config contains rates for two membership
# 等级：0 = 普通，1 = 高级。 / levels: 0 = Regular, 1 = Premium

# ----------------------------
# 制作成功率 / Crafting chances:
# ----------------------------
# 触发暴击制作的百分比概率（应用于第一步） / Chance in percent to have a critical procraft (applied on first step)
# 默认值：15.0, 30.0 / Default: 15.0, 30.0
gameserver.rates.crafting.crit_chances = 100.0, 100.0

# 触发连锁制作的百分比概率（应用于后续步骤） / Chance in percent to have a combo procraft (applied on subsequent steps)
# 默认值：25.0, 50.0 / Default: 25.0, 50.0
gameserver.rates.crafting.combo_crit_chances = 100.0, 100.0

# ----------------------------
# 强化成功率 / Enchantment chances:
# ----------------------------
# 魔石基础成功率百分比 / Base manastone chance in percent
# 默认值：75.0, 75.0 / Default: 75.0, 75.0
gameserver.rates.manastone_chances = 90.0, 90.0

# 强化石与物品等级和品质完全匹配时的强化基础成功率百分比（会根据差异偏移） / Enchanting base chance in percent, if the stone exactly matches the item level and quality (will divert according to the difference)
# 默认值：65.0, 65.0 / Default: 65.0, 65.0
gameserver.rates.enchantment_stone.base_chances = 90.0, 90.0

# 物品已增幅时的强化成功率百分比（该倍率固定） / Enchanting chance in percent if the item is amplified (this rate is fixed)
# 默认值：50.0, 50.0 / Default: 50.0, 50.0
gameserver.rates.enchantment_stone.amplified_chances = 90.0, 90.0

# 突破成功率百分比（羽毛除外） / Tempering chance in percent (except for plumes)
# 默认值：65.0, 65.0 / Default: 65.0, 65.0
gameserver.rates.tampering_chances = 90.0, 90.0

# ----------------------------
# 等级经验倍率 / Level XP rates:
# ----------------------------
# 单人PvE经验 / Solo PvE XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.xp.solo = 2.0, 3.0

# 组队PvE经验 / Group PvE XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.xp.group = 1.5, 2.5

# 任务经验 / Quest XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.xp.quest = 1.5, 2.5

# 采集经验 / Gathering XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.xp.gathering = 2.0, 3.0

# 制作经验 / Crafting XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.xp.crafting = 2.0, 3.0

# PvP经验 / PvP XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.xp.pvp = 2.0, 3.0

# ----------------------------
# 技能经验倍率 / Skill level XP rates:
# ----------------------------
# 采集技能经验 / Gathering Skill XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.skill_xp.gathering = 2.0, 3.0

# 制作技能经验 / Crafting Skill XP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.skill_xp.crafting = 2.0, 3.0

# ----------------------------
# AP倍率 / AP rates:
# ----------------------------
# PvP AP获得 / PvP AP Gain
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.ap.pvp.gain = 1.0, 2.0

# PvP AP损失 / PvP AP Loss
# 默认值：1.0, 1.0 / Default: 1.0, 1.0
gameserver.rates.ap.pvp.loss = 1.0, 1.0

# PvE AP倍率 / PvE AP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.ap.pve = 100.0, 200.0

# 任务AP / Quest AP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.ap.quest = 100.0, 100.0

# 德雷得奇安AP / Dredgion AP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.ap.dredgion = 100.0, 100.0

# ----------------------------
# GP倍率 / GP rates:
# ----------------------------
# GP获得 / GP Gain
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.gp.gain = 50.0, 50.0

# ----------------------------
# DP倍率 / DP rates:
# ----------------------------
# PvE DP倍率 / PvE DP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.dp.pve = 1.0, 2.0

# PvP DP倍率 / PvP DP
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.dp.pvp = 1.0, 2.0

# ----------------------------
# 任务基纳倍率 / Quest Kinah rates:
# ----------------------------
# 普通 / Regular
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.kinah.quest = 100.0, 200.0

# ----------------------------
# 掉落倍率 / Drop rates:
# ----------------------------
# 掉落 / Drop
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.drop = 3.0, 4.0

# ----------------------------
# 采集数量倍率 / Gathering count rates:
# ----------------------------
# 采集数量倍率 / Gathering count multiplier
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.gathering.count = 3.0, 4.0

# ----------------------------
# PvP竞技场奖励倍率 / PvP Arena reward rates:
# ----------------------------
# PvP孤独竞技场奖励倍率 / PvP Discipline Arena Reward rates
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.pvparena.discipline = 1.0, 2.0

# PvP混沌竞技场奖励倍率 / PvP Chaos Arena Reward rates
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.pvparena.chaos = 1.0, 2.0

# PvP和谐竞技场AP/神圣徽章倍率 / PvP Harmony Arena AP/Crucible Insignia rates
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.pvparena.harmony = 1.0, 2.0

# PvP荣耀竞技场AP/GP倍率 / PvP Glory Arena AP/GP rates
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.pvparena.glory = 1.0, 2.0

# ----------------------------
# 出售限制倍率 / Sell Limit rates:
# ----------------------------
# 普通 / Regular
# 默认值：1.0, 2.0 / Default: 1.0, 2.0
gameserver.rates.sell_limit = 1.0, 2.0
