#
# ----------------------------
# 安全配置 / Security config's:
# ----------------------------

# 反作弊保护 / Anti Hack Protection

# AION.bin大小检查 / AION.bin size check
gameserver.security.aion.bin.check = false

# 启用/禁用非法传送校验 / Enable\disable validation for illegal teleportation
gameserver.security.antihack.teleportation = false

# 启用/禁用客户端注入加速校验 / Enable\disable validation for speed increase client inject
gameserver.security.antihack.speedhack = false

# 加速作弊检测计数器 / Speedhack detect counter
gameserver.security.antihack.speedhack.counter = 5

# 启用/禁用忽略异常状态作弊校验 / Enable\disable validation for ignoring abnormals hack
gameserver.security.antihack.abnormal = false

# 异常状态作弊告警计数器 / Abnormal hack alarm counter
# 0会完全禁止作弊者移动，但也会记录一些无辜玩家（不要与 punish = 3 一起使用！） / 0 will not allow hackers to move at all, but will logg some unguilty players (don't use this with punish = 3!)
gameserver.security.antihack.abnormal.counter = 1

# 惩罚 / Punishment
# 0 - 添加日志记录 / 0 - add log record
# 1 - 记录日志并将作弊者放回上次已知位置 / 1 - log and put cheater back on last known position
# 2 - 记录日志并将作弊者放回上次已知位置（达到 speedhack.counter * 3 后踢出游戏） / 2 - log and put cheater back on last known position (after 'speedhack.counter * 3' kick player from game)
# 3 - 记录日志并踢出游戏 / 3 - log and kick player from game
gameserver.security.antihack.punish = 0

# 检查无动作作弊（防止技能过早执行，并将可疑玩家记录到审计日志） / Check for no-animation hacks (prevents premature skill executions and logs suspicious players to audit log)
# 默认值：true / Default: true
gameserver.security.check_animations = true

# 踢出未通过ping检查的玩家（可能加速作弊） / Kick players who don't pass the ping check (possible speedhack)
# 默认值：true / Default: true
gameserver.security.pingcheck.kick = true

# ----------------------------
# 验证码配置 / CAPTCHA config's:
# ----------------------------
# 启用验证码服务 / Enable CAPTCHA service
# 默认值：false / Default: false
gameserver.security.captcha.enable = false

# 设置验证码出现条件 / Set CAPTCHA appearance
# OD = 奥德采集时 / OD = when OD
# ALL = 所有采集时 / ALL = when all gathering
# 默认值：OD / Default: OD
gameserver.security.captcha.appear = OD

# 设置验证码出现概率 / Set CAPTCHA appearance rate
# 默认值：5 (%) / Default: 5 (%)
gameserver.security.captcha.appear.rate = 5

# 设置采集封禁时间（秒） / Set extraction ban time in seconds
# 默认值：3000 （50分钟） / Default: 3000 (50 min)
gameserver.security.captcha.extraction.ban.time = 3000

# 设置采集封禁追加时间（秒） / Set extraction ban add time in seconds
# 默认值：600 （10分钟） / Default: 600 (10 min)
gameserver.security.captcha.extraction.ban.add.time = 600

# 设置奖励飞行时间 / Set Bonus flypoint time
# 默认值：5 / Default: 5
gameserver.security.captcha.bonus.fp.time = 5

# ----------------------------
# 角色密码配置 / PassKey config's:
# ----------------------------
# 启用角色密码 / Enable character passkey
# 默认值：false / Default: false
gameserver.security.passkey.enable = false

# 设置允许输入错误密码的最大次数 / Enter the maximum number of incorrect password set
# 默认值：5 / Default: 5
gameserver.security.passkey.wrong.maxcount = 5

# ----------------------------
# 刷屏/洪泛配置 / Flood config's:
# ----------------------------
# 刷屏消息 / Flood Message
# 消息最小间隔 / Message min interval
# 默认值：1 sec / Default: 1 sec
gameserver.security.flood.delay = 1

# 刷屏消息达到次数后封禁 / Ban after flooding messages
# 默认值：6 / Default: 6
gameserver.security.flood.msg = 6

# ----------------------------
# 其他配置 / Others config's:
# ----------------------------

# 启用飞行传送校验器 / Enable fly teleport validator
# 默认值：false / Default: false
gameserver.security.validation.flypath = false

# 问卷校验时间（测试） / Surveys validation time (test)
# 默认值：20 / Default: 20
gameserver.security.survey.delay.minute = 20

# 多开限制模式： / Restriction mode for multi-clienting:
# NONE - 允许玩家在每台电脑登录多个账号 / NONE - Players are allowed to log in multiple accounts per computer
# FULL - 每台电脑只允许登录一个账号 / FULL - Players are allowed to log in one account per computer
# SAME_FACTION - 允许每台电脑登录多个账号，但只能登录同阵营角色 / SAME_FACTION - Players are allowed to log in multiple accounts per computer, but only log in characters of the same faction
gameserver.security.multi_clienting.restriction_mode = NONE

# 允许无视配置限制登录的MAC地址列表，逗号分隔。 / Comma separated list of MAC addresses that are allowed to log in regardless of the configured restrictions.
gameserver.security.multi_clienting.ignored_mac_addresses =

# 如果多开限制为同阵营，则在对立阵营所有角色 / If multi-clienting is restricted to the same faction, logging in characters of one faction will be denied until all characters of the opposite
# 离线达到指定时间前，会拒绝登录本阵营角色。 / faction have been offline for the specified amount of time.
gameserver.security.multi_clienting.faction_switch_cooldown_minutes = 20

# 启用对锁定到SSD或HDD序列号账号的登录检查。 / Enable login checks for accounts that are locked to a SSD or HDD serial number.
# 锁定账号只能从具有对应序列号驱动器上的游戏客户端登录。 / Locked accounts can only be logged in from the game client on a drive with the locked serial number.
# 账号可通过 `.lock` 玩家命令手动锁定和解锁。 / Accounts can be manually locked and unlocked via the `.lock` player command.
# 默认值：false / Default: false
gameserver.security.hdd_serial_lock.enable = false

# 登录时自动将未锁定账号锁定到客户端SSD或HDD序列号 / Automatically lock unlocked accounts on login to the client's SSD or HDD serial number
# 默认值：false / Default: false
gameserver.security.hdd_serial_lock.auto_lock = false
