#
# ----------------------------
# 基础要塞战配置 / Basic siege config's:
# ----------------------------

# 启用要塞战系统 / Enable siege system
# 默认值：true / Default: true
gameserver.siege.enable = true

# 启用自动龙族突袭 / Enable automatic Balaur Assaults
gameserver.siege.assault.enable = true

# 龙族突袭概率倍率（浮点数） / Rate for Balaur assaults chance(float)
# 默认值：1 / Default: 1
gameserver.siege.assault.rate = 1

# 莫尔特努斯刷新时间 / Moltenus spawn time
# 默认值：0 0 22 ? * SUN / Default: 0 0 22 ? * SUN
gameserver.moltenus.time = 0 0 22 ? * SUN

# 要塞BOSS生命倍率（1.0 = 100%，0.5 = 50%） / Fortress boss health multiplier (1.0 = 100%, 0.5 = 50%)
# 默认值：1.0 / Default: 1.0
gameserver.siege.health.multiplier.fortress = 1.0

# 神器BOSS生命倍率（1.0 = 100%，0.5 = 50%） / Artifact boss health multiplier (1.0 = 100%, 0.5 = 50%)
# 默认值：1.0 / Default: 1.0
gameserver.siege.health.multiplier.artifact = 1.0

# 基地BOSS生命倍率（1.0 = 100%，0.5 = 50%） / Base boss health multiplier (1.0 = 100%, 0.5 = 50%)
# 默认值：1.0 / Default: 1.0
gameserver.siege.health.multiplier.base = 1.0

# 要塞战和突袭难度倍率 / Siege and Assault difficulty multiplier
# 默认值：1.0 / Default: 1.0
gameserver.siege.difficulty.multiplier = 1.0

# 泛盖亚每阵营玩家限制 / Panesterra player limit per faction
# 默认值：100 / Default: 100
gameserver.siege.panesterra.maxplayers = 100

# 阿赫塞里翁飞行每阵营玩家限制 / Ahserion's Flight player limit per faction
# 默认值：100 / Default: 100
gameserver.siege.panesterra.ahserion.maxplayers = 100

# 阿赫塞里翁飞行日程 / Ahserion's Flight schedule
# 默认值：0 50 18 ? * * / Default: 0 50 18 ? * *
gameserver.siege.panesterra.ahserion.time = 0 50 18 ? * SUN

# 每次激活恢复的治疗量百分比 / Heal amount(%) recovered with each activation
# 默认值：0.01 / Default: 0.01
gameserver.siege.door.repair.heal.percent = 0.01

# 龙族要塞战成功时启用/禁用玩家奖励 / Enables/Disables rewards for players if balaur succeed in sieges
# 默认值：false / Default: false
gameserver.siege.reward.balaur.victory = false

# 清理地点时忽略工作人员 / Ignore staff members on location clear
# 默认值：false / Default: false
gameserver.siege.ignore_staff_on_location_clear = false