#
# ----------------------------
# 线程配置 / Thread config's:
# ----------------------------

# 专用于处理即时任务的线程数。 / Number of threads that are dedicated to handle instant tasks.
# 值为0表示自动。自动模式下，该数量通常等于 Runtime#availableProcessors() 报告的逻辑CPU核心数，但 / A value of 0 means auto. On auto, the number is usually equal to the number of logical CPU cores as reported by Runtime#availableProcessors(), but
# 不会少于4。 / never less than four.
# 默认值：0 / Default: 0
gameserver.thread.base_pool_size = 0

# 专用于处理计划任务的线程数。 / Number of threads that are dedicated to handle scheduled tasks.
# 值为0表示自动。自动模式下，该数量通常等于 Runtime#availableProcessors() 报告的逻辑CPU核心数，但 / A value of 0 means auto. On auto, the number is usually equal to the number of logical CPU cores as reported by Runtime#availableProcessors(), but
# 不会少于4。 / never less than four.
# 默认值：0 / Default: 0
gameserver.thread.scheduled_pool_size = 0

# 如果任何线程完成任务耗时超过此值，则记录警告。单位为毫秒。 / Logs a warning if any thread needs longer than this time to finish a task. Time in milliseconds.
# 默认值：5000 / Default: 5000
gameserver.thread.runtime = 5000

# 为即时线程池使用更高线程优先级 / Use higher thread priorities for instant thread pool
# 注意：Linux下必须使用root，并添加参数：-XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=1 / Note: in Linux you must be root and use switches: -XX:+UseThreadPriorities -XX:ThreadPriorityPolicy=1
# 默认值：false / Default: false
gameserver.thread.usepriority = false